/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx_hal.h"

#define UART2_PINS_POSRT	(GPIOA)
#define UART2_TX_PIN		(GPIO_PIN_2)
#define UART2_RX_PIN		(GPIO_PIN_3)

void InitUart2(void);
void SystemClock_Config(void);


UART_HandleTypeDef tUart2 = {0};

int __io_putchar(int ch)
{
	HAL_UART_Transmit(&tUart2, (uint8_t*)&ch, 1, 100);

	return ch;
}

int main(void)
{
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	/* Initialize UART2. */
	InitUart2();

	/* Super loop. */
	while(1)
	{
		printf("Printf is being used !\r\n");

		HAL_Delay(500);
	}
}


void InitUart2(void)
{
	// PA2 -- > Uart2 TX
	// PA3 -- > Uart2 RX

	GPIO_InitTypeDef tUart2Gpio = {0};

	/* Enable Clock for GPIOA peripheral */
	__HAL_RCC_GPIOA_CLK_ENABLE();

	/* Enable Clock for USART2 peripheral */
	__HAL_RCC_USART2_CLK_ENABLE();

	/* GPIO pins act as alternate function pins. */
	tUart2Gpio.Pin = (UART2_RX_PIN | UART2_TX_PIN);

	/* Select the mode as alternate function. */
	tUart2Gpio.Mode = GPIO_MODE_AF_PP;

	/* Alternate function 7. */
	tUart2Gpio.Alternate = GPIO_AF7_USART2;

	/* No pull up resistor. */
	tUart2Gpio.Pull = GPIO_NOPULL;

	/* Configure speed as very high. */
	tUart2Gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;

	/* Init the GPIO pins. */
	HAL_GPIO_Init(UART2_PINS_POSRT, &tUart2Gpio);

	/* Configure UART. */
	/* Select the UART instance. */
	tUart2.Instance = USART2;

	/* Set the baud rate. */
	tUart2.Init.BaudRate = 115200;

	/* Select word length as 8 bits. */
	tUart2.Init.WordLength = UART_WORDLENGTH_8B;

	/* Select stop bits. */
	tUart2.Init.StopBits = UART_STOPBITS_1;

	/*Set Parity. */
	tUart2.Init.Parity = UART_PARITY_NONE;

	/* Select the mode. */
	tUart2.Init.Mode = UART_MODE_TX_RX;

	/* Set the hw flow control. */
	tUart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;

	/* Set the over sampling. */
	tUart2.Init.OverSampling = UART_OVERSAMPLING_16;

	HAL_UART_Init(&tUart2);

	return;
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
