/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"

#define LED_PORT	(GPIOA)
#define BTN_PORT	(GPIOC)

#define LED_PIN		(GPIO_PIN_5)
#define BTN_PIN		(GPIO_PIN_13)


static void InitLedGpio(void);
static void InitBtnGpioIt(void);


void SystemClock_Config(void);

int main(void)
{
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2();
	InitLedGpio();
	InitBtnGpioIt();

	/* Super loop. */
	while(1)
	{

	}
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}

/*
 * Configure PA5 as output.
 */
static void InitLedGpio(void)
{
	GPIO_InitTypeDef tLedGpio = {0};


	/* Enable Clock*/
	__HAL_RCC_GPIOA_CLK_ENABLE();

	tLedGpio.Pin = LED_PIN;
	tLedGpio.Mode = GPIO_MODE_OUTPUT_PP;
	tLedGpio.Pull = GPIO_NOPULL;
	tLedGpio.Speed = GPIO_SPEED_FREQ_LOW;


	HAL_GPIO_Init(LED_PORT, &tLedGpio);

	return;
}

static void InitBtnGpioIt(void)
{
	GPIO_InitTypeDef tBtnGpio = {0};


	/* Enable Clock*/
	__HAL_RCC_GPIOC_CLK_ENABLE();

	tBtnGpio.Pin = BTN_PIN;
	tBtnGpio.Mode = GPIO_MODE_IT_RISING;
	tBtnGpio.Pull = GPIO_NOPULL;
	tBtnGpio.Speed = GPIO_SPEED_FREQ_LOW;


	HAL_GPIO_Init(BTN_PORT, &tBtnGpio);

	/* Configure EXTI */
	HAL_NVIC_SetPriority(EXTI15_10_IRQn, 0, 0);
	HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);

	return;
}

void EXTI15_10_IRQHandler(void)
{
	HAL_GPIO_EXTI_IRQHandler(BTN_PIN);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
}
