/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"
#include "uart1.h"


I2C_HandleTypeDef tI2c1;


void SystemClock_Config(void);
void InitI2C1Master(void);

uint8_t ucTXBuff[] = "Hello Arduino, This is STM32L476RG \r\n";

int main(void)
{
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2();

	InitI2C1Master();

	//HAL_I2C_Master_Transmit(&tI2c1, (0x55 << 1), ucTXBuff, sizeof(ucTXBuff), HAL_MAX_DELAY);

	/* Super loop. */// Add to your main function for debugging
	while(1)
	{
	    HAL_StatusTypeDef res;
	    //uint32_t startTime = HAL_GetTick();

	    // Check if I2C bus is ready first
	    if (HAL_I2C_IsDeviceReady(&tI2c1, (0x55 << 1), 3, 100) == HAL_OK) {
	        Uart2TxData((uint8_t*)"Device Ready\r\n", 14);

	        res = HAL_I2C_Master_Transmit(&tI2c1, (0x55 << 1), ucTXBuff, sizeof(ucTXBuff)-1, 1000);
	        if (res == HAL_OK) {
	            Uart2TxData((uint8_t*)"I2C TX OK\r\n", 11);
	        } else {
	            Uart2TxData((uint8_t*)"I2C TX FAIL: ", 13);
	            // Add error detail reporting
	            if (res == HAL_ERROR) Uart2TxData((uint8_t*)"HAL_ERROR\r\n", 12);
	            else if (res == HAL_BUSY) Uart2TxData((uint8_t*)"HAL_BUSY\r\n", 10);
	            else if (res == HAL_TIMEOUT) Uart2TxData((uint8_t*)"HAL_TIMEOUT\r\n", 13);
	        }
	    } else {
	        Uart2TxData((uint8_t*)"Device Not Ready\r\n", 18);
	    }

	    HAL_Delay(2000);  // Wait 2 seconds between attempts
	}
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

// Update GPIO configuration for standard I2C1 pins (PB6/SCL, PB7/SDA)
void InitI2C1Master(void)
{
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_I2C1_CLK_ENABLE();

    GPIO_InitTypeDef tI2c1Gpio = {0};
    tI2c1Gpio.Pin = GPIO_PIN_6 | GPIO_PIN_7;  // Use PB6 and PB7
    tI2c1Gpio.Mode = GPIO_MODE_AF_OD;
    tI2c1Gpio.Alternate = GPIO_AF4_I2C1;
    tI2c1Gpio.Pull = GPIO_PULLUP;
    tI2c1Gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;

    HAL_GPIO_Init(GPIOB, &tI2c1Gpio);

    tI2c1.Instance = I2C1;
    tI2c1.Init.Timing = 0x10909CEC;  // Standard timing for 100kHz
    tI2c1.Init.OwnAddress1 = 0;
    tI2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    tI2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    tI2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    tI2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;

    if (HAL_I2C_Init(&tI2c1) != HAL_OK) {
        Uart2TxData((uint8_t*)"I2C Init Failed\r\n", 17);
    } else {
        Uart2TxData((uint8_t*)"I2C Init Success\r\n", 18);
    }
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
