/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"
#include "uart1.h"


#define RTC_ASYNCH_PREDIV    0x7f
#define RTC_SYNCH_PREDIV  	 0xf9

#define BKP_FLAG 	0x8888

void rtc_calender_show(void);
void rtc_calender_config();
void rtc_init();

uint8_t time[32];
uint8_t date[32];


RTC_HandleTypeDef rtc_handle;


void SystemClock_Config(void);

int main(void)
{
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2();

    __HAL_RTC_RESET_HANDLE_STATE(&rtc_handle);

    rtc_init();
    rtc_calender_config();

    if(HAL_RTCEx_BKUPRead(&rtc_handle,RTC_BKP_DR0)!=BKP_FLAG)
    {
    	rtc_calender_config();
    }

	/* Super loop. */
    while (1)
    {
    	rtc_calender_show();

    	HAL_Delay(500);
    }
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

void rtc_init(){
	RCC_OscInitTypeDef RCC_Oscinit;
	RCC_PeriphCLKInitTypeDef RCC_pclk;

	RCC_Oscinit.OscillatorType = RCC_OSCILLATORTYPE_LSI | RCC_OSCILLATORTYPE_LSE;
	RCC_Oscinit.LSEState = RCC_LSE_OFF;
	RCC_Oscinit.LSIState =RCC_LSI_ON;

	HAL_RCC_OscConfig(&RCC_Oscinit);

	RCC_pclk.PeriphClockSelection = RCC_PERIPHCLK_RTC;
	RCC_pclk.RTCClockSelection = RCC_RTCCLKSOURCE_LSI;

	HAL_RCCEx_PeriphCLKConfig(&RCC_pclk);

	__HAL_RCC_RTC_ENABLE();

	rtc_handle.Instance = RTC;
	rtc_handle.Init.HourFormat = RTC_HOURFORMAT_24;
	rtc_handle.Init.AsynchPrediv = 0x7F;	//127
	rtc_handle.Init.SynchPrediv = 0xF9;		//249
	rtc_handle.Init.OutPut = RTC_OUTPUT_DISABLE;

	HAL_RTC_Init(&rtc_handle);

}


void rtc_calender_config(){
	RTC_DateTypeDef datestruct;
	RTC_TimeTypeDef timestrcut;

	datestruct.Year = 0x25;
	datestruct.Month = RTC_MONTH_SEPTEMBER;
	datestruct.Date = 0x10;
	datestruct.WeekDay = RTC_WEEKDAY_WEDNESDAY;

	HAL_RTC_SetDate(&rtc_handle, &datestruct, RTC_FORMAT_BCD);

	timestrcut.Hours = 9;
	timestrcut.Minutes = 0x2B;
	timestrcut.Seconds = 0x00;
	timestrcut.TimeFormat = RTC_HOURFORMAT12_AM;
	timestrcut.DayLightSaving = RTC_DAYLIGHTSAVING_NONE;
	timestrcut.StoreOperation = RTC_STOREOPERATION_RESET;

	HAL_RTC_SetTime(&rtc_handle, &timestrcut, RTC_FORMAT_BCD);

	//Write to Backup Register
	HAL_RTCEx_BKUPWrite(&rtc_handle, RTC_BKP_DR0, BKP_FLAG);

}

void rtc_calender_show(void)
{
	uint16_t uhTimeSize = 0;
	uint16_t uhDateSize = 0;
	RTC_DateTypeDef datestruct;
	RTC_TimeTypeDef timestrcut;

	HAL_RTC_GetDate(&rtc_handle, &datestruct, RTC_FORMAT_BIN);
	HAL_RTC_GetTime(&rtc_handle, &timestrcut, RTC_FORMAT_BIN);

	uhTimeSize = sprintf((char*)time,"Time : %02d:%02d:%02d\r\n",timestrcut.Hours,timestrcut.Minutes,timestrcut.Seconds);
	uhDateSize = sprintf((char*)date,"Date : %02d:%02d:%02d\r\n",datestruct.Date,datestruct.Month,datestruct.Year);

	Uart2TxData(time, uhTimeSize);
	Uart2TxData(date, uhDateSize);

	return;

}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
