/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"
#include "uart1.h"


SPI_HandleTypeDef tSpi1;
DMA_HandleTypeDef tDmaSpi1Tx;
DMA_HandleTypeDef tDmaSpi1Rx;

void SystemClock_Config(void);
void InitSPI1(void);


uint8_t ucSpiTxBuff[] = "Hello STM32 SPI1 Module\r\n";
uint16_t uhTxBuffSize = sizeof(ucSpiTxBuff);
uint8_t ucSpiRxBuff[100];


int main(void)
{
	uint8_t ucResBuff[100] = {0};
	uint16_t uhResSize = 0;
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2();

	InitSPI1();

	HAL_SPI_TransmitReceive_DMA(&tSpi1, ucSpiTxBuff, ucSpiRxBuff, uhTxBuffSize);

	/* Super loop. */
	while(1)
	{
		if(strcmp((char*)ucSpiTxBuff, (char*)ucSpiRxBuff) == 0)
		{
			uhResSize = sprintf((char*)ucResBuff, "SPI Worked ");
			memcpy(ucResBuff + uhResSize, ucSpiRxBuff, uhTxBuffSize);
			ucResBuff[uhResSize + uhTxBuffSize] = '\r';
			ucResBuff[uhResSize + uhTxBuffSize + 1] = '\n';

			uhResSize = (uhResSize + uhTxBuffSize + 2);
		}
		else
		{
			uhResSize = sprintf((char*)ucResBuff, "Some issues happened in SPI communication\r\n");
		}

		Uart2TxData(ucResBuff, uhResSize);
		HAL_Delay(500);
	}
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

void InitSPI1(void)
{
    GPIO_InitTypeDef tSPIGpio = {0};

    /* Enable Clocks */
    __HAL_RCC_SPI1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_DMA1_CLK_ENABLE();

    /*
     * SPI1 Pins:
     * MISO ---> PA6
     * MOSI ---> PA7
     * SCK  ---> PA5
     */
    tSPIGpio.Pin       = (GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7);
    tSPIGpio.Mode      = GPIO_MODE_AF_PP;
    tSPIGpio.Pull      = GPIO_NOPULL;
    tSPIGpio.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
    tSPIGpio.Alternate = GPIO_AF5_SPI1;
    HAL_GPIO_Init(GPIOA, &tSPIGpio);

    /* Configure SPI1 peripheral */
    tSpi1.Instance               = SPI1;
    tSpi1.Init.Mode              = SPI_MODE_MASTER;
    tSpi1.Init.Direction         = SPI_DIRECTION_2LINES;
    tSpi1.Init.DataSize          = SPI_DATASIZE_8BIT;
    tSpi1.Init.CLKPolarity       = SPI_POLARITY_LOW;
    tSpi1.Init.CLKPhase          = SPI_PHASE_1EDGE;
    tSpi1.Init.NSS               = SPI_NSS_SOFT;
    tSpi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8;
    tSpi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    tSpi1.Init.TIMode            = SPI_TIMODE_DISABLE;
    tSpi1.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
    tSpi1.Init.CRCLength         = SPI_CRC_LENGTH_DATASIZE;
    tSpi1.Init.NSSPMode          = SPI_NSS_PULSE_DISABLE;
    HAL_SPI_Init(&tSpi1);

    /* ---------------- DMA CONFIG ---------------- */

    /* SPI1_RX ---> DMA1_Channel2 */
    tDmaSpi1Rx.Instance                 = DMA1_Channel2;
    tDmaSpi1Rx.Init.Request             = DMA_REQUEST_1;  // SPI1_RX request
    tDmaSpi1Rx.Init.Direction           = DMA_PERIPH_TO_MEMORY;
    tDmaSpi1Rx.Init.PeriphInc           = DMA_PINC_DISABLE;
    tDmaSpi1Rx.Init.MemInc              = DMA_MINC_ENABLE;
    tDmaSpi1Rx.Init.PeriphDataAlignment = DMA_PDATAALIGN_BYTE;
    tDmaSpi1Rx.Init.MemDataAlignment    = DMA_MDATAALIGN_BYTE;
    tDmaSpi1Rx.Init.Mode                = DMA_NORMAL;
    tDmaSpi1Rx.Init.Priority            = DMA_PRIORITY_LOW;
    HAL_DMA_Init(&tDmaSpi1Rx);

    /* SPI1_TX ---> DMA1_Channel3 */
    tDmaSpi1Tx.Instance                 = DMA1_Channel3;
    tDmaSpi1Tx.Init.Request             = DMA_REQUEST_1;  // SPI1_TX request
    tDmaSpi1Tx.Init.Direction           = DMA_MEMORY_TO_PERIPH;
    tDmaSpi1Tx.Init.PeriphInc           = DMA_PINC_DISABLE;
    tDmaSpi1Tx.Init.MemInc              = DMA_MINC_ENABLE;
    tDmaSpi1Tx.Init.PeriphDataAlignment = DMA_PDATAALIGN_BYTE;
    tDmaSpi1Tx.Init.MemDataAlignment    = DMA_MDATAALIGN_BYTE;
    tDmaSpi1Tx.Init.Mode                = DMA_NORMAL;
    tDmaSpi1Tx.Init.Priority            = DMA_PRIORITY_LOW;
    HAL_DMA_Init(&tDmaSpi1Tx);

    /* Link DMA handles to SPI */
    __HAL_LINKDMA(&tSpi1, hdmarx, tDmaSpi1Rx);
    __HAL_LINKDMA(&tSpi1, hdmatx, tDmaSpi1Tx);

    /* ---------------- NVIC CONFIG ---------------- */

    /* DMA IRQs */
    HAL_NVIC_SetPriority(DMA1_Channel2_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(DMA1_Channel2_IRQn);

    HAL_NVIC_SetPriority(DMA1_Channel3_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(DMA1_Channel3_IRQn);

    /* SPI1 IRQ */
    //HAL_NVIC_SetPriority(SPI1_IRQn, 1, 0);
    //HAL_NVIC_EnableIRQ(SPI1_IRQn);
}


void DMA1_CH2_IRQHandler(void)
{
	HAL_DMA_IRQHandler(&tDmaSpi1Rx);
}
void DMA1_CH3_IRQHandler(void)
{
	HAL_DMA_IRQHandler(&tDmaSpi1Tx);
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
