/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"
#include "uart1.h"

#define BUFFER_SIZE		32
#define DMA_CHANNEL		DMA1_Channel5
#define DMA_IRQ			DMA1_Channel5_IRQn
#define DMA_IRQ_HANDLER	DMA1_CH5_IRQHandler


DMA_HandleTypeDef tDmaHandle;


uint32_t uiSrcBuff[BUFFER_SIZE] = {
    0x00000001, 0x12345678, 0xAABBCCDD, 0xDEADBEEF,
    0xCAFEBABE, 0x0F0F0F0F, 0xFFFFFFFF, 0x80000000,
    0x7FFFFFFF, 0x13579BDF, 0x2468ACE0, 0x0BADBEEF,
    0x11223344, 0x55667788, 0x99AABBCC, 0xDDEEFF00,
    0x01020304, 0xABCD1234, 0xF00DBABE, 0xC001D00D,
    0xFEEDFACE, 0xFACEFEED, 0xBAADF00D, 0xDEADC0DE,
    0x0A0B0C0D, 0x10203040, 0x90807060, 0x5566AABB,
    0xCCDDEEFF, 0x31415926, 0x27182818, 0xDEADC0FF
};

uint32_t uiDestBuff[BUFFER_SIZE] = {0};




void SystemClock_Config(void);
static void DmaConfig(void);

int main(void)
{
	uint8_t ucResBuff[100] = {0};
	uint16_t uhresSize = 0;
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2();

	DmaConfig();

	/* Super loop. */
	while(1)
	{
		if(0 == memcmp(uiSrcBuff, uiDestBuff, sizeof(uiSrcBuff)))
		{
			uhresSize = sprintf((char*)ucResBuff, "Transfer completed properly\r\n");
		}
		else
		{
			uhresSize = sprintf((char*)ucResBuff, "Some Error in DMA transfer \r\n");
		}

		Uart2TxData(ucResBuff, uhresSize);
		HAL_Delay(500);
	}
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}

static void DmaConfig(void)
{
	__HAL_RCC_DMA1_CLK_ENABLE();

	tDmaHandle.Instance 				= DMA_CHANNEL;
	tDmaHandle.Init.Request 			= DMA_REQUEST_2;
	tDmaHandle.Init.Direction 			= DMA_MEMORY_TO_MEMORY;
	tDmaHandle.Init.PeriphInc 			= DMA_PINC_ENABLE;
	tDmaHandle.Init.MemInc 				= DMA_MINC_ENABLE;
	tDmaHandle.Init.PeriphDataAlignment = DMA_PDATAALIGN_WORD;
	tDmaHandle.Init.MemDataAlignment 	= DMA_MDATAALIGN_WORD;
	tDmaHandle.Init.Mode 				= DMA_NORMAL;
	tDmaHandle.Init.Priority 			= DMA_PRIORITY_HIGH;

	HAL_DMA_Init(&tDmaHandle);

	HAL_NVIC_SetPriority(DMA_IRQ, 0, 0);
	HAL_NVIC_EnableIRQ(DMA_IRQ);

	HAL_DMA_Start_IT(&tDmaHandle, (uint32_t)&uiSrcBuff,
			(uint32_t)&uiDestBuff, BUFFER_SIZE);
	return;
}

void DMA_IRQ_HANDLER(void)
{
	HAL_DMA_IRQHandler(&tDmaHandle);
}
