/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"
#include "uart1.h"


void SystemClock_Config(void);

uint32_t uiRxCnt1;
uint32_t uiTxCnt1;

uint32_t uiRxCnt2;
uint32_t uiTxCnt2;

uint8_t ucRxBuff1[100];
uint8_t ucTxBuff1[] = "This is from uart1\r\n";

uint8_t ucRxBuff2[100];
uint8_t ucTxBuff2[] = "Thus is from uart2\r\n";


int main(void)
{
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2IT();
	InitUart1();

	Uart1TxData(ucTxBuff1, sizeof(ucTxBuff1));
	Uart1RxData(ucRxBuff1, sizeof(ucTxBuff1));

	Uart2TxDataIT(ucTxBuff2, sizeof(ucTxBuff2));
	Uart2RxDataIT(ucRxBuff2, sizeof(ucTxBuff2));

	/* Super loop. */
	while(1)
	{

	}
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        //Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        //Error_Handler();
    }
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
	if(huart->Instance == USART1)
	{
		uiRxCnt1 += 1;
	}
	else if(huart->Instance == USART2)
	{
		uiRxCnt2 += 1;
	}
}

void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
	if(huart->Instance == USART1)
	{
		uiTxCnt1 += 1;
	}
	else if(huart->Instance == USART2)
	{
		uiTxCnt2 += 1;
	}
}
