/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l4xx_hal.h"

#define LED_PORT	(GPIOA)
#define BTN_PORT	(GPIOC)

#define LED_PIN		(GPIO_PIN_5)
#define BTN_PIN		(GPIO_PIN_13)


static void InitLedGpio(void);
static void InitBtnGpio(void);

//BTN --> PC13 BUS = AHB2 --> RCC_AHB2_ENR --> bit 0
//LED --> PA5  BUS = AHB2 --> RCC_AHB2_ENR --> bit 2

int main(void)
{

	uint8_t ucBtnPinState = 0;

	/* Initialize HAL. */
	HAL_Init();

	/* Init LED GPIO*/
	InitLedGpio();

	/* Init Button GPIO. */
	InitBtnGpio();


	HAL_GPIO_WritePin(LED_PORT, LED_PIN, 1);

	while(1)
	{
		ucBtnPinState = HAL_GPIO_ReadPin(BTN_PORT, BTN_PIN);

		HAL_GPIO_WritePin(LED_PORT, LED_PIN, ucBtnPinState);
	}
}

/*
 * Configure PA5 as output.
 */
static void InitLedGpio(void)
{
	GPIO_InitTypeDef tLedGpio = {0};


	/* Enable Clock*/
	__HAL_RCC_GPIOA_CLK_ENABLE();

	tLedGpio.Pin = LED_PIN;
	tLedGpio.Mode = GPIO_MODE_OUTPUT_PP;
	tLedGpio.Pull = GPIO_NOPULL;
	tLedGpio.Speed = GPIO_SPEED_FREQ_LOW;


	HAL_GPIO_Init(LED_PORT, &tLedGpio);

	return;
}

static void InitBtnGpio(void)
{
	GPIO_InitTypeDef tBtnGpio = {0};


	/* Enable Clock*/
	__HAL_RCC_GPIOC_CLK_ENABLE();

	tBtnGpio.Pin = BTN_PIN;
	tBtnGpio.Mode = GPIO_MODE_INPUT;
	tBtnGpio.Pull = GPIO_NOPULL;
	tBtnGpio.Speed = GPIO_SPEED_FREQ_LOW;


	HAL_GPIO_Init(BTN_PORT, &tBtnGpio);

	return;
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
